# Colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Options
set -g mouse on
set -g renumber-windows on
set -g mode-keys vi

# StatusLine
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=colour28,fg=colour255"
set -g status-right "#H | %Y-%m-%d %H:%M"

# KeyBindings
unbind w
unbind &

bind b next-window
bind Space choose-window

bind C-s split-window -v
bind C-v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-b last-pane

bind -r C-h resize-pane -L 6
bind -r C-l resize-pane -R 6
bind -r C-j resize-pane -D 6
bind -r C-k resize-pane -U 6

bind w kill-pane
bind C-w kill-window

bind y copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
