# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: !!null vim
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    o: repo view --web
    co: pr checkout
    searchpr: |-
        !gh api graphql -F owner=':owner' -F repo=':repo' -F hash=$1 -f query='
          query($repo:String!, $owner:String!, $hash:String) {
            repository(name: $repo, owner: $owner) {
              object(expression: $hash) {
                ... on Commit {
                  associatedPullRequests(first: 1) {
                    edges {
                      node {
                        number
                      }
                    }
                  }
                }
              }
            }
          }
        ' | jq .data.repository.object.associatedPullRequests.edges[0].node.number
    openpr: '!gh searchpr $1 | xargs -I ISSUE_NUMBER gh pr view ISSUE_NUMBER --web'
