" NeoBundle {{{
set nocompatible
filetype off
filetype plugin indent off
if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'rking/ag.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'tomasr/molokai'

call neobundle#end()

filetype on
filetype indent on
filetype plugin on
" }}}

" Common {{{
set nocompatible " Vi互換モードをオフ
set number "行番号表示
set backspace=2 " backspaceで改行を削除
set nowrap " 折り返し無効
set smartindent " 改行時に自動的にインデントを挿入
set clipboard+=unnamed " ヤンクしたテキストをクリップボードコピー

" ファイル開いた時に、前回終了時の行で起動
autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif

" Color
syntax on
colorscheme molokai

" brackets
set showmatch " 波括弧入力時の対応する括弧を表示
set list listchars=trail:_ " 行の後ろの空白文字を表示
set showmatch " 閉じ括弧が入力されたとき、対応する括弧を表示する

" Tab
set ts=2 sw=2 sts=0 " タブは半角2文字
set expandtab " タブの代わりに空白文字表示
set autoindent " オートインデント
set showtabline=4 " タブを常に表示

" Completion
set wildmenu " コマンド補完を有効
set omnifunc=syntaxcomplete#Complete " オムニ補完あり

" Search
set hlsearch " 検索にヒットした文字列をハイライト
set ignorecase " 検索時に大文字小文字を無視
set smartcase " 大文字で検索された場合は大文字だけヒット
set incsearch " インクリメンタルサーチを有効

" Option
set autoread " vimの外でのファイル変更を自動的に反映させる
set noswapfile " バッファのスワップファイルを作成しない
set nobackup " バックアップファイルを作成しない
set visualbell t_vb= " ビープ音をオフ

" Line
set modeline " モードラインを有効にする
set modelines=3 " 3行目までをモードラインとして検索する
set laststatus=2 "ステータスラインを常に表示
set showcmd "入力中のコマンドをステータスに表示

" Status Line
set statusline=%f%m%=%y[%{&fileencoding}][%{&fileformat}]

" KeyMapping
nnoremap ; :
nnoremap : ;

nnoremap s <Nop>
nnoremap sj <C-w>j
nnoremap sk <C-w>k
nnoremap sl <C-w>l
nnoremap sh <C-w>h
nnoremap sn gt
nnoremap sp gT
nnoremap st :<C-u>tabnew<CR>
nnoremap sT :<C-u>Unite tab<CR>
nnoremap ss :<C-u>sp<CR>
nnoremap sv :<C-u>vs<CR>
nnoremap sq :<C-u>q<CR>
nnoremap sQ :<C-u>bd<CR>
nnoremap sb :<C-u>Unite buffer_tab -buffer-name=file<CR>
nnoremap sB :<C-u>Unite buffer -buffer-name=file<CR>

" autocmd vimenter * NERDTree
nnoremap <silent><C-e> :NERDTreeToggle<CR>
let g:NERDTreeDirArrows=0
let g:NERDTreeWinPos = "right"

" Ag(The Silver Searcher)
let g:unite_enable_start_insert = 1 " insert modeで開始
let g:unite_enable_ignore_case = 1 " 大文字小文字を区別しない
let g:unite_enable_smart_case = 1
" grep
nnoremap <silent> ,g  :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
nnoremap <silent> ,cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
nnoremap <silent> ,r  :<C-u>UniteResume search-buffer<CR>
if executable('ag')
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
  let g:unite_source_grep_recursive_opt = ''
endif
" }}}

" INSERT_MODE {{{
inoremap <silent> jj <ESC>
inoremap <C-e> <END>
inoremap <C-a> <HOME>
" }}}
