" ----------------------------------------
" plugin - NeoBundle
" ----------------------------------------
set nocompatible
filetype off
filetype plugin indent off
if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
    call neobundle#begin(expand('~/.vim/bundle/'))
    NeoBundleFetch 'Shougo/neobundle.vim'
    call neobundle#end()
endif

NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'tpope/vim-markdown'
NeoBundle 'rking/ag.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'tomasr/molokai'

filetype on
filetype indent on
filetype plugin on

" ----------------------------------------
" Common
" ----------------------------------------
set nocompatible " Vi互換モードをオフ
set number "行番号表示
set backspace=2 " backspaceで改行を削除
set nowrap " 折り返し無効
set smartindent " 改行時に自動的にインデントを挿入
set clipboard+=unnamed " ヤンクしたテキストをクリップボードコピー

" ファイル開いた時に、前回終了時の行で起動
autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif

" brackets
set showmatch " 波括弧入力時の対応する括弧を表示
set list listchars=trail:_ " 行の後ろの空白文字を表示
set showmatch " 閉じ括弧が入力されたとき、対応する括弧を表示する

" Tab
set ts=2 sw=2 sts=0 " タブは半角2文字
set expandtab " タブの代わりに空白文字表示
set autoindent " オートインデント
set showtabline=4 " タブを常に表示

" Completion
set wildmenu " コマンド補完を有効
set omnifunc=syntaxcomplete#Complete " オムニ補完あり

" Search
set hlsearch " 検索にヒットした文字列をハイライト
set ignorecase " 検索時に大文字小文字を無視
set smartcase " 大文字で検索された場合は大文字だけヒット
set incsearch " インクリメンタルサーチを有効

" Option
set autoread " vimの外でのファイル変更を自動的に反映させる
set noswapfile " バッファのスワップファイルを作成しない
set nobackup " バックアップファイルを作成しない
set visualbell t_vb= " ビープ音をオフ

" Line
set modeline " モードラインを有効にする
set modelines=3 " 3行目までをモードラインとして検索する
set laststatus=2 "ステータスラインを常に表示
set showcmd "入力中のコマンドをステータスに表示

" Status Line
set statusline=%f%m%=%y[%{&fileencoding}][%{&fileformat}]

" Moving
noremap H b
noremap J }
noremap K {
noremap L w
" 対応する括弧に移動
nnoremap ( %
nnoremap ) %

" .vimrcを再読み込み
nnoremap <Leader>r :source ~/.vimrc<CR>

" Color
syntax on
colorscheme molokai

" autocmd vimenter * NERDTree
nmap <silent> <C-e>  :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let g:NERDTreeDirArrows=0
"let g:NERDTreeMouseMode=0
let g:NERDTreeWinPos = "right"

" Ag(The Silver Searcher)
let g:unite_enable_start_insert = 1 " insert modeで開始
let g:unite_enable_ignore_case = 1 " 大文字小文字を区別しない
let g:unite_enable_smart_case = 1
" grep
nnoremap <silent> ,g  :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
nnoremap <silent> ,cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
nnoremap <silent> ,r  :<C-u>UniteResume search-buffer<CR>
if executable('ag')
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
  let g:unite_source_grep_recursive_opt = ''
endif

" Indent
autocmd Filetype javascript setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd Filetype ruby setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

" ----------------------------------------
" INSERT MODE
" ----------------------------------------
inoremap <silent> jj <ESC>
inoremap <C-e> <END>
inoremap <C-a> <HOME>
