[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'
on_cmd = 'Denite'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1