# https://yazi-rs.github.io/docs/tips/#close-input-by-esc
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Back to the root of the current Git repository"

# https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
