theme = "tokyonight"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.insert]
C-c = "normal_mode"
C-a = "goto_line_start"
C-e = "goto_line_end_newline"

[keys.select]
C-c = "normal_mode"

[keys.normal]
H = "goto_previous_buffer"
L = "goto_next_buffer"
X = ["extend_line_up", "extend_to_line_bounds"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after" ]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-J = ["extend_to_line_bounds", "yank", "paste_after"]
A-K = ["extend_to_line_bounds", "yank", "paste_before"]

# Using `yazi` within Helix
# https://github.com/helix-editor/helix/discussions/12934
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.normal.space]
w = ":write"
x = ":buffer-close"
i = { h = ":toggle lsp.display-inlay-hints" }
