# ========================================
#
# .tmux.conf
#
# setting file of tmux
#
# ========================================

# ----------------------------------------
# Prefix
# ----------------------------------------
set -g prefix C-t
unbind C-b

# ----------------------------------------
# Options
# ----------------------------------------
set -g default-terminal  screen-256color
set -g default-command "reattach-to-user-namespace -l $SHELL"
set -g mouse-select-pane on
set -g status on
set -g base-index 1
setw -g mode-keys vi

# ----------------------------------------
# Visual
# ----------------------------------------
# status line
set -g status-fg    default
set -g status-bg    colour237
set -g status-attr  default
set -g status-left  '[#S]'
set -g status-right '[#(loadaverage)][%Y-%m-%d %H:%M]'
set -g status-left-length  60
set -g status-right-length 60

# window-status-current
setw -g window-status-current-fg   colour237
setw -g window-status-current-bg   white
setw -g window-status-current-attr bold

# pane border
set -g pane-border-fg        colour237
set -g pane-active-border-fg default

# ウィンドウを閉じたときにインデックス番号を詰める
set -g renumber-windows on

# ----------------------------------------
# KeyBindings
# ----------------------------------------
# reload .tmux.conf
unbind r
bind r source-file ~/.tmux.conf \; display-message 'source-file ~/.tmux.conf'

# - Window
# 新ウィンドウ作成
bind c new-window
# ウィンドウ選択画面
unbind w
bind Space choose-window
# ウィンドウ終了
unbind &
bind K kill-window
# 全ウィンドウ終了
bind C-b kill-session

# - Pane
# 分割していたペインそれぞれをWindowに
unbind 1
bind 1 break-pane
# ペインの縦分割
bind 2 split-window -v
# ペインの横分割
bind 3 split-window -h
# ペイン終了
bind k kill-pane
# ペイン番号表示
bind i display-panes

# ペインの移動
# Shift + 上下左右でペインを移動できるようにする。(＜Prefix＞不要)
# 行頭に"bind -n"をつけるとPrefixが不要になる。
bind -n S-left select-pane -L
bind -n S-down select-pane -D
bind -n S-up select-pane -U
bind -n S-right select-pane -R

# move lase pane
# http://d.hatena.ne.jp/naoya/20130108/1357630895
# bind C-t last-pane
bind C-t run "tmux last-pane || tmux last-window || tmux new-window"

# ペインリサイズ関連vi風
bind -r C-h resize-pane -L 6
bind -r C-l resize-pane -R 6
bind -r C-j resize-pane -D 6
bind -r C-k resize-pane -U 6
bind -r s swap-pane -U
# ペインの入れ替え
unbind {
unbind }

# ----------------------------------------
# copy mode
# ----------------------------------------
# Setup 'v' to begin selection as in Vim
bind y copy-mode
bind -t vi-copy v begin-selection
bind -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
bind -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
