# general
export PATH=/opt/local/bin:$PATH
export PATH=/opt/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/bin:$PATH

# node.js
export PATH=$HOME/.nodebrew/current/bin:$PATH

# Ruby
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

# Java
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
# export PATH=$PATH:$JAVA_HOME/bin

# Go
export GOPATH=$HOME

# Haskell
export PATH=$HOME/.cabal/bin:$PATH

# homebrew-cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"
