# ====================================
# .zshrc
# ====================================

# ------------------------------------
# Oh-my-zsh settings
# ------------------------------------.
ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.oh-my-zsh-custom

ZSH_THEME="beer"

plugins=(
alias
function
git
npm
global
)

source $ZSH/oh-my-zsh.sh
